apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: tripviewer
        image: registrytkw2929.azurecr.io/poi:1.0.0
        env:
          - name: "SQL_USER"
            value: "sqladmintKw2929"
          - name: "SQL_PASSWORD"
            value: "gW5an2Bs3"
          - name: "SQL_SERVER"
            value: "mydrivingDB"
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
        ports:
          - name: api
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: poi
