apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    app: user-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrytkw2929.azurecr.io/user-java:1.0.0
        env:
          - name: "PORT"
            value: "80"
          - name: "CONFIG_FILES_PATH"
            value: "http://endpoint.you.specify(:port)"
        envFrom:
          - secretRef:
              name: dev-db-secret
        ports:
          - name: api
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: user-java
