apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
  namespace: api
  labels:
    app: userjava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - name: userjava
        image: registrytkw2929.azurecr.io/userjava:1.0.0
        env:
          - name: "PORT"
            value: "80"
          - name: "CONFIG_FILES_PATH"
            value: "http://endpoint.you.specify(:port)"
          - name: "SQL_USER"
            value: "sqladmintKw2929"
          - name: "SQL_PASSWORD"
            value: "gW5an2Bs3"
          - name: "SQL_SERVER"
            value: "sqlservertkw2929.database.windows.net"
          - name: "SQL_DBNAME"
            value: "mydrivingDB"
        ports:
          - name: api
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: userjava
